version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app
      DB_PASS: app
      DB_NAME: appdb
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data:
