version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/appdb?schema=public
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data:
